import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import WalletConnectCard from "../components/connectorCards/WalletConnectCard";
import MetaMaskCard from "../components/connectorCards/MetaMaskCard";
import { useQuery } from "@apollo/client";
import { useProfileQuery } from "~/profile.generated";
import {
  PublicationsPostFragment,
  usePublicationsQuery,
} from "~/publications.generated";
import { Post } from "~/graphql-types";

export default function Home() {
  const { data } = useProfileQuery();
  const { data: publications } = usePublicationsQuery();
  const posts = publications?.publications.items as PublicationsPostFragment[];
  console.log(data);
  console.log(publications?.publications.items);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <WalletConnectCard />
        <MetaMaskCard />

        {posts?.map((node) => (
          <div key={node.id}>
            <div>{node.metadata.name}</div>
            <div>{node.metadata.description}</div>
            <div>{node.metadata.content}</div>
          </div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
